# Generated by Django 3.2.5 on 2023-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200)),
                ('port_number', models.IntegerField()),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
